version: '3.1'
services:
  stats-server:
    build: stats/stats-server
    image: stats
    container_name: stats_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/shareit
      - SPRING.DATASOURCE.USERNAME=root
      - SPRING.DATASOURCE.PASSWORD=123

  stats-db:
    image: postgres:14-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123

  ewm-service:
    build: main
    image: main
    container_name: main_container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5433/shareit


  ewm-db:
    image: postgres:14-alpine
    container_name: ewm_db
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123